name: basic workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.*
      - name: Install dependencies
        run: dotnet restore --nologo
      - name: Build project
        run: dotnet build --nologo --no-restore
      - name: Run tests
        run: dotnet test --no-build --no-restore --nologo
      - name: Packs nuget
        run: dotnet pack --no-build --no-restore --nologo
