name: basic workflow

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.*
      - name: Install GitVersion
        shell: bash
        run: dotnet tool install --global gitversion.tool
      - name: Calculate Semantic Version
        shell: bash
        run: dotnet gitversion /output buildserver /showvariable SemVer /updateassemblyinfo AssemblyInfo.cs /ensureassemblyinfo
      - name: Install dependencies
        run: dotnet restore --nologo
      - name: Build project
        run: dotnet build --nologo --no-restore --configuration Release
      - name: Run tests
        run: dotnet test --no-build --no-restore --nologo --configuration Release
      - name: Packs nuget
        run: dotnet pack --no-build --no-restore --nologo --configuration Release --output $GITHUB_WORKSPACE/nuget
      - name: Binary publish
        run: dotnet publish --no-build --no-restore --nologo --configuration Release --output $GITHUB_WORKSPACE/publish source/**/*.csproj
      - name: Publish artifact
        uses: actions/upload-artifact@v2
        with:
          name: "nuget"
          path: "/home/runner/work/MathCalculator/MathCalculator/nuget/*"
      - name: Publish binary artifact
        uses: actions/upload-artifact@v2
        with:
          name: "nightly"
          path: "/home/runner/work/MathCalculator/MathCalculator/publish/*"
      - name: Publish to debug feed
        run: dotnet nuget push $GITHUB_WORKSPACE/nuget/*.nupkg -k $NUGET_API_KEY -s https://nuget.kritikos.io/v3/index.json
        env:
          NUGET_API_KEY: ${{ secrets.KRITIKOS_API_KEY }}
